# Generated by Django 2.1.3 on 2018-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0004_geoloc_itemlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoloc',
            name='postal_code',
            field=models.IntegerField(unique=True),
        ),
    ]
