# Generated by Django 2.1.3 on 2018-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0005_auto_20181129_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
