# Generated by Django 2.1.3 on 2018-11-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0006_auto_20181129_1642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemlocation',
            unique_together={('location', 'item')},
        ),
    ]
