# Generated by Django 2.1.3 on 2018-11-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0007_auto_20181129_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='shopping_list',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
